import logging
from typing import Any, Optional


class TextareaLogHandler(logging.StreamHandler):
    log_format: str = ...
    time_format: str = ...
    max_buffer: int = ...
    min_delay: float = ...
    stream: Any = ...
    widget: Any = ...
    last_time: Any = ...

    def __init__(self, level: Any=...) -> None:
        ...

    def emit(self, record: Any):
        ...


class panel():
    widget: Any = ...
    ncols: int = ...
    devices: Any = ...
    children: Any = ...

    def __new__(cls, source: int=..., ncols: int=...):
        ...

def log_progress(
    sequence: Any,
    every: Optional[Any]=...,
    size: Optional[Any]=...,
    title: Optional[Any]=...
) -> None:
    ...
