import logging
from ._backends import VISADevice as VISADevice
from ._host import Host as Host
from ._rack import Rack as Rack
from .util import show_messages as show_messages
from ipywidgets import HTML as HTML, IntProgress as IntProgress, VBox as VBox
from typing import Any

skip_state_by_type: Any

def single(inst: Any, inst_name: Any): ...

class TextareaLogHandler(logging.StreamHandler):
    log_format: str = ...
    time_format: str = ...
    max_buffer: int = ...
    min_delay: float = ...
    stream: Any = ...
    widget: Any = ...
    last_time: Any = ...
    def __init__(self, level: Any = ...) -> None: ...
    def emit(self, record: Any): ...

class panel:
    widget: Any = ...
    ncols: int = ...
    devices: Any = ...
    children: Any = ...
    def __new__(cls, source: int = ..., ncols: int = ...): ...
