from . import _traits

class any(_traits.Any): ...
class bool(_traits.Bool): ...
class float(_traits.Float): ...
class int(_traits.Int): ...
class complex(_traits.Complex): ...
class str(_traits.Unicode): ...
class bytes(_traits.Bytes): ...
class list(_traits.List): ...
class tuple(_traits.Tuple): ...
class dict(_traits.Dict): ...
class Path(_traits.Path): ...
class NetworkAddress(_traits.NetworkAddress): ...
